package io.eventbob.core.eventrouting;

/**
 * Standard metadata keys for EventBob event routing and observability.
 *
 * <p>Metadata is stored in {@link Event#getMetadata()} as a Map. This class defines
 * the standard keys that EventBob routing infrastructure and adapters recognize.
 *
 * <h2>Standard Metadata vs Parameters</h2>
 * <ul>
 *   <li><b>Metadata</b> - routing and infrastructure concerns (method, path template, correlation)
 *   <li><b>Parameters</b> - business data and path parameter values
 * </ul>
 *
 * <h2>Example Usage</h2>
 * <pre>
 * Event event = Event.builder()
 *   .target("inventory-service")
 *   .metadata(Map.of(
 *     MetadataKeys.METHOD, "POST",
 *     MetadataKeys.PATH, "update-available/{catalog}/{sku}",
 *     MetadataKeys.CORRELATION_ID, UUID.randomUUID().toString(),
 *     MetadataKeys.TRACE_ID, traceContext.traceId()
 *   ))
 *   .parameters(Map.of(
 *     "catalog", "electronics",
 *     "sku", "ABC123"
 *   ))
 *   .build();
 * </pre>
 *
 * <h2>Transport-Specific Metadata</h2>
 * <p>Transport adapters may add their own metadata using namespaced keys.
 * For example, an HTTP adapter might use keys like {@code http.status} or
 * {@code http.content-type}. The core domain does not define or constrain
 * transport-specific metadata - adapters are free to use any naming convention.
 */
public final class MetadataKeys {

  // ========== Core Routing Metadata ==========

  /**
   * Correlation ID for tracking request/response pairs across macro boundaries.
   *
   * <p>Generated by the initiating adapter and propagated through the entire event chain.
   * Used by adapters to match responses to pending requests.
   *
   * <p><b>Type:</b> String (typically UUID)
   * <br><b>Example:</b> {@code "550e8400-e29b-41d4-a716-446655440000"}
   * <br><b>Required:</b> For cross-macro calls and async patterns
   */
  public static final String CORRELATION_ID = "correlation-id";

  /**
   * Address where the response should be sent.
   *
   * <p>Format depends on the caller's adapter:
   * <ul>
   *   <li>HTTP adapter: {@code "macro-name.http-adapter-thread-id"}
   *   <li>Queue adapter: {@code "response-queue-name"}
   *   <li>In-process: may be omitted (direct return)
   * </ul>
   *
   * <p><b>Type:</b> String
   * <br><b>Example:</b> {@code "macro-read-path.http-adapter-thread-5"}
   * <br><b>Required:</b> For async patterns where response is routed separately
   */
  public static final String REPLY_TO = "reply-to";

  // ========== Operation Semantics ==========

  /**
   * Operation method or type.
   *
   * <p>Interpretation depends on transport:
   * <ul>
   *   <li>HTTP-like: {@code GET}, {@code POST}, {@code PUT}, {@code DELETE}, {@code PATCH}
   *   <li>gRPC: method name (e.g., {@code "GetUser"}, {@code "UpdateInventory"})
   *   <li>Queue: message type or operation (e.g., {@code "OrderCreated"})
   * </ul>
   *
   * <p><b>Type:</b> String (free-form, no enum constraint)
   * <br><b>Example:</b> {@code "POST"}
   */
  public static final String METHOD = "method";

  /**
   * Resource path template.
   *
   * <p>Contains a template with placeholders for path parameters. Actual parameter values
   * should be in {@link Event#getParameters()}, not in metadata.
   *
   * <p><b>Type:</b> String
   * <br><b>Example:</b> {@code "update-available/{catalog}/{sku}"}
   * <br><b>Note:</b> Path parameter values like {@code catalog="electronics"} go in parameters
   */
  public static final String PATH = "path";

  // ========== Observability ==========

  /**
   * Distributed trace ID for correlation across services.
   *
   * <p>Propagated across all macro-services and adapters to enable end-to-end request tracing.
   * Compatible with OpenTelemetry and similar distributed tracing systems.
   *
   * <p><b>Type:</b> String (hex-encoded trace ID)
   * <br><b>Example:</b> {@code "4bf92f3577b34da6a3ce929d0e0e4736"}
   */
  public static final String TRACE_ID = "trace-id";

  /**
   * Span ID for this specific event within the distributed trace.
   *
   * <p>Each event handler should create a new span ID when processing an event,
   * linking it to the parent span via the trace ID.
   *
   * <p><b>Type:</b> String (hex-encoded span ID)
   * <br><b>Example:</b> {@code "00f067aa0ba902b7"}
   */
  public static final String SPAN_ID = "span-id";

  private MetadataKeys() {
    throw new AssertionError("No instances");
  }
}
